replicaCount: 3

image:
  repository: b0ce4f43-kr1-registry.container.nhncloud.com/delivery/delivery-app
  tag: 6a22f5e

# false 이면 Deployment, true 이면 Rollout 이 생성됩니다.
progressiveDelivery: false

canary:
  steps:
    - setWeight: 25
    - pause: { duration: 30s }
    - setWeight: 50
    - pause: { duration: 30s }
    - setWeight: 100
  progressDeadlineSeconds: 60
  progressDeadlineAbort: true
